server {
    listen 80;
    server_name demo.autokore.space;
    root /usr/share/nginx/html/demo;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store";
    }
}

server {
    listen 80;
    server_name autokore.space www.autokore.space;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}
