services:
  lilop-site:
    container_name: lilop-site
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
    expose:
      - "80"
    networks:
      - lilop-network

networks:
  lilop-network:
    external: true
